/* This is a C Program by Jacqueline Plata for CS1311 3/05/2024
 *
 * ---Asks the user for 7 unique numbers 
 *  (only positive integers) from 1 to 50.
 * ---Generate 7 random and unique numbers from 1 to 50. 
 * ---Make a function called bubble that sorts a list of 7 numbers using  
 * the bubble sort algorithm ( call bubble twice, once for each array). 
 * ---Print out the user's guess in the order given by the user and  
 * in numeric order. 
 * ---Print out the random numbers you generated in the order they 
 * were generated and in numeric order. 
 * --- Let the user know how many and which numbers matched the 
 * lottery numbers.
 * 
 *         !~                       
  ^:      !@&!      :^               
 ~CSP:   !#@&#!   :JVK~               
  .C@P    ^@&^    J@P.                
   .S@^   :@&:   ^@V.                  
    ^@P   :@&:   K@^                  
     G@:  :@&:  :@G                   
     J@BM##@@##MN@J                   
      ^5!~!@&!~!5^                   
          ^@&^                       
          ^@&^                       
          ^**^       
  */
 
 
 
 #include<stdio.h>
 
 
 
 /* Printing an array of 7 elements */
 void print_array( int array[])
 {
 	int i; /* Used to count through array */
 	/* For loop to print out each element in array */
 	for( i = 0; i < 7; i++)
 		{
 			printf(" %i, ", array[i]);
 		}
 }
 
 
 
 int Check_for_Duplicate(int x, int array[])
 {
 	int i, duplicate = 0; /* index to array, value to send back */
 	
 	for( i = 0; i < 7; i++) /* for each item in array check for x */
 	{
 		if(x == array[i]) /* if there is a duplicate */
 		{
 			duplicate = 1; 
 		}
 	}
 	return duplicate; 
 }
 
 
 
 void Bubble_Sort(int list[])
 {
 		int sorted = 1, a = 7, temp; /* flag to see if sorted or not, an index */
 		int i; /* Used to go through the for loop */ 
 		
 		do  {  /* while list is not sorted */
 			sorted = 1; /* assume sorted */
 			for( i = 0; i < a-1 ; i++) /* check each ajacent pair */
 			{
 				if(list[i] > list[i+1])  /* if first greater than second swap */
 				{ /* swap list items */
 					temp = list[i];
 					list[i] = list[i+1];
 					list[i+1] = temp;
 					sorted = 0; /* It is not yet sorted */
 				}
 			}
 		}while( sorted == 0); /* List was not sorted */
 }
 
 
 
 void main(void)
 {
 	int n; /* Used to check for duplicates in users numbers */
 	int r; /* Used to check for duplicates in random array */
 	int num[7] = {0,0,0,0,0,0,0}; /* Used to hold the numbers the user entered */
	int count = 0; /* Used to get 7 numbers in while loop*/ 
	int unique; /* Used to check for Duplicates */
	int randunique; /* Used to check for Duplicates in random array*/
	int index; /* Counter for for loop */
	int randnum[7]; /* Used to hold the random generated numbers */
	int x, j, count1 = 0; /*Used to check if any values are correct and counts how many */
 	
 	
 	
 	printf( "This is a Lottery Program\n"
	 		"where you the user is going to guess the numbers to the lottery.\n" 
			"Enter 7 unique positive numbers when asked\n"
			"and see if the numbers match the random\n"
			"7 lottery numbers generated by the computer then\n"
			"we will see if the numbers you entered\n" 
			"match the lottery generated numbers.");
			
			
			
	while(count < 7) /* Getting 7 numbers from the user */
	{
		printf("\n\nEnter a number between 1 and 50: ");
 		scanf("%d", &n); /* Read in guessed number from user */
 		printf("You typed %i.\n", n);
		
		
		
		unique = Check_for_Duplicate(n,num); /* Checking for Duplicate */
 		
 		
 		/*if there is no duplicate */ 
 		if(unique == 0  &&  n >= 1  && n <= 50) /* n is an ok value */
 			{
 				num[count] = n; /* put into the array */
 				count = count + 1;
 			}
 		else /* If there is a duplicate */
 		{
 			printf("\n%i is a duplicate or out of range.\n\n", n);
 		}
 	}
 	printf("\n");
 	
 	
 	
 	printf("\n\nThe list you entered is: \n");
	print_array(num); /* Print numbers */
		
		
		
	printf("\n\nThe list you entered sorted numerically: \n");
 	Bubble_Sort(num); /* Sort numbers */
 	print_array(num); /* Print numbers */
 		
 		

 	srand(time(NULL)); /* Seed the random number generator */
 	
 	rand();	/* To get more random looking values */
 	
 	while(index < 7) /* Check if random numbers have duplicates */
	{
		r = rand()%50+1 ; /* put into the array */
		
		randunique = Check_for_Duplicate(r,randnum); /* Check for duplicates */
 		
 		if(unique == 0) /* n is an ok value */
 			{
 				randnum[index] = rand()%50+1 ; /* put into the array */
 				index = index + 1;
 			}
 	}



 	printf("\n\nThe Lottey list is: \n");
 	print_array(randnum); /* Print random numbers array */
 	
 	
 	
 	printf("\n\nThe Lottey list sorted numerically: \n");
 	Bubble_Sort(randnum); /* Sort random numbers array */
 	print_array(randnum); /* Print random numbers array */
 	
 	
 
 	/* Check how many numbers were guessed correctly but seeing if 
 		the numbers from the lottery and numbers guessed match */
 	for(x=0; x<7; x++) 
 	{
 		for(j=0; j<7; j++)
 		{
 			if(num[j] == randnum[x]) /* See if they match */
 			{
 				printf( "\n\n%i is a number you guessed correct.\n", num[j]); 
				count1 = count1 + 1;
 			}
 		}
 	}
 	
 	
 	
 	if(count1 == 0) /* No numbers where counted as correct */
 		{
 			printf("\n\nYou guessed no correct numbers.\n\n");
 			
 		}
 	else /* some number was guessed correctly */
 		{
 			printf("\nYou have %i correct guess(es).", count1);
 		}
 }
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
